steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/192626383583/gke-repo/quickstart-image:latest', './app1']
      id: 'Build Docker Image'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/192626383583/gke-repo/quickstart-image:latest']
      id: 'Push Docker Image'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/192626383583/gke-repo/flask-image:latest', './app2']
      id: 'Build Docker Image2'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/192626383583/gke-repo/flask-image:latest']
      id: 'Push Docker Image2'

  - name: 'google/cloud-sdk:latest'
    entrypoint: 'sh'
      args:
          - -xe
            - -c
              - |
                    gcloud deploy apply --file deploy/pipeline.yaml --region=us-central1
                        gcloud deploy apply --file deploy/dev.yaml --region=us-central1
                            gcloud deploy releases create 'app-release-${SHORT_SHA}' --delivery-pipeline=gke-cicd-pipeline --region=us-central1 --skaffold-file=skaffold.yaml

      options:
          logging: CLOUD_LOGGING_ONLY

