steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
          'build', 
              '-t', 
                  'us-central1-docker.pkg.dev/hallowed-web-448714-p7/gke-repo/quickstart-image',
                      '.'
                        ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
          'push', 
              'us-central1-docker.pkg.dev/hallowed-web-448714-p7/gke-repo/quickstart-image'
                ]

    images:
      - 'us-central1-docker.pkg.dev/hallowed-web-448714-p7/gke-repo/quickstart-image'

